In [1]:
from src.train_utils import generate_trajectory_dataset
import torch

In [2]:

val_dataset = generate_trajectory_dataset("validation", obs_len=5, pred_len=10)

2023-12-18 12:11:59,501 - trainer - DEBUG - Defaulting to root: /Users/josevalderrama/Projects/NFLBIGDATA/resources/


100%|██████████| 1256/1256 [00:04<00:00, 284.48it/s]

2023-12-18 12:12:07,117 - datasets - INFO - Finished grouping 145 sequences
2023-12-18 12:12:07,156 - datasets - INFO - Processing 145 plays ranging from 60 to 70 lengths...


In [3]:
print(val_dataset.mean_speed, val_dataset.std_speed)

s    2.517447
dtype: float64 s    1.856074
dtype: float64


In [4]:
print(val_dataset.mean_acc, val_dataset.std_acc)

a    1.749545
dtype: float64 a    1.247467
dtype: float64


In [5]:
print(val_dataset.mean_distance_traveled, val_dataset.std_distance_traveled)

dis    0.254945
dtype: float64 dis    0.186658
dtype: float64


In [6]:
print(val_dataset.num_features)

21


In [7]:
dataloader = torch.utils.data.DataLoader(val_dataset, batch_size=1)

In [10]:
from src.metrics import compute_bivariate_params

for batch in dataloader:

    V_obs, A_obs, obs_traj = batch["data"]
    truth_labels = batch["labels"]

    V_truth = truth_labels["trajectory_relative"]
    V_x = torch.cumsum(V_obs[..., 0], dim=1) + obs_traj[:, 0, :, 0]
    V_y = torch.cumsum(V_obs[..., 1], dim=1) + obs_traj[:, 0, :, 1]
    print(V_x[0].shape)
    print(V_y[0])

    *_, cov, mean = compute_bivariate_params(V_pred=V_pred)
    mvnormal = torch.distributions.multivariate_normal.MultivariateNormal(mean,cov)
    V_pred = mvnormal.sample()
    
    torch.cumsum(V_pred[..., 0], dim=1) + obs_traj[:, 0, :, 0]
    break

torch.Size([5, 22])
tensor([[ 26.4500,  26.5600,  32.7400,  29.6000,  14.0100,  26.5500,  25.8500,
          35.2800,  22.7400,  21.3500,  28.0000,  28.5500,  25.0800,  23.6000,
          31.4800,  31.1300,  33.0300,  22.3700,  29.7500,  26.6200,  20.6500,
          14.7900],
        [ 52.9200,  53.1200,  65.3900,  59.2000,  28.0600,  53.1000,  51.7000,
          70.7700,  45.3300,  42.7200,  56.0000,  57.1000,  50.1600,  47.2000,
          62.9600,  62.2600,  66.0600,  44.7400,  59.5000,  53.2300,  41.4400,
          29.5800],
        [ 79.3900,  79.6700,  97.9500,  88.8000,  42.1400,  79.6500,  77.5500,
         106.4600,  67.7600,  64.1000,  84.0000,  85.6500,  75.2400,  70.8000,
          94.4300,  93.3900,  99.0900,  67.1100,  89.2500,  79.8400,  62.4100,
          44.3700],
        [105.8600, 106.2200, 130.4100, 118.3900,  56.2500, 106.2000, 103.4000,
         142.3500,  90.0300,  85.5000, 112.0000, 114.2000, 100.3200,  94.4000,
         125.9000, 124.5200, 132.1200,  89.4700, 11

In [12]:
traj = sample['labels']['trajectory']
print(traj[0, 0, 0, :])

tensor([ 0.6323,  0.2734, -0.1010, -0.4646, -0.1336,  0.7126,  0.0680,  0.0769,
         0.2203,  0.0000,  0.0000,  0.0000,  6.0000,  0.8000,  0.2500,     nan,
         0.5417,  0.0000,  0.0000,  0.0000,  0.0000])


In [10]:
print(traj[0, 0, 0, 0])

tensor(0.2945)


In [2]:
import torch
tensor = torch.Tensor([[0.1, 0.7]])
print(tensor[tensor > 0.5])

tensor([0.7000])
